# Generated by Django 5.2 on 2025-10-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatmessage_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsession",
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("last_message_timestamp"),
                        descending=True,
                        nulls_first=True,
                    ),
                    "-created_at",
                ]
            },
        ),
    ]
