# Generated by Django 5.2 on 2025-11-13 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoSetMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "video_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique video ID matching vectordb entry (e.g., 'screen_1234567890')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "video_set_id",
                    models.CharField(
                        db_index=True,
                        help_text="Groups multiple video chunks into one recording session (e.g., UUID)",
                        max_length=255,
                    ),
                ),
                (
                    "timestamp",
                    models.BigIntegerField(
                        db_index=True,
                        help_text="Unix timestamp in milliseconds, used for sorting within set",
                    ),
                ),
                (
                    "collection_version",
                    models.CharField(
                        blank=True,
                        help_text="Optional collection version for A/B testing",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this video recording",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_metadata",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Set Metadata",
                "verbose_name_plural": "Video Set Metadata",
                "ordering": ["video_set_id", "timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "video_set_id"], name="collection__user_id_6b1dd2_idx"
                    ),
                    models.Index(
                        fields=["video_set_id", "timestamp"], name="collection__video_s_8c5dad_idx"
                    ),
                ],
            },
        ),
    ]
