# Generated by Django 5.2 on 2025-11-27 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreenRecording",
            fields=[
                (
                    "video_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique video ID matching VectorDB entry (e.g., 'screen_1234567890')",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "encrypted_content",
                    models.TextField(
                        help_text="Encrypted JSON payload containing video_base64 and metadata"
                    ),
                ),
                (
                    "video_set_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optional: Groups multiple video chunks into one recording session (e.g., UUID)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Unix timestamp in milliseconds, used for sorting within video sets",
                        null=True,
                    ),
                ),
                (
                    "collection_version",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optional collection version for testing different client versions",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this screen recording",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screen_recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Screen Recording",
                "verbose_name_plural": "Screen Recordings",
                "db_table": "collection_screenrecording",
                "ordering": ["video_set_id", "timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "collection_version"], name="collection__user_id_51c1a4_idx"
                    ),
                    models.Index(
                        fields=["user", "video_set_id"], name="collection__user_id_84d4b1_idx"
                    ),
                    models.Index(
                        fields=["video_set_id", "timestamp"], name="collection__video_s_ac0bbe_idx"
                    ),
                ],
            },
        ),
    ]
