name: PR Labeler

on:
  pull_request_target:
    types: [opened, synchronize, labeled, unlabeled, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
